# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 120, 531, 124))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.sitesGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.sitesGridLayout.setContentsMargins(0, 0, 0, 0)
        self.sitesGridLayout.setObjectName("sitesGridLayout")
        self.blockedSitesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.blockedSitesLabel.setObjectName("blockedSitesLabel")
        self.sitesGridLayout.addWidget(self.blockedSitesLabel, 1, 0, 1, 1)
        self.blockedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.blockedLabel.setObjectName("blockedLabel")
        self.sitesGridLayout.addWidget(self.blockedLabel, 1, 1, 1, 1)
        self.deleteButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.deleteButton2.setObjectName("deleteButton2")
        self.sitesGridLayout.addWidget(self.deleteButton2, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.deleteButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.deleteButton1.setObjectName("deleteButton1")
        self.sitesGridLayout.addWidget(self.deleteButton1, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.addNewButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addNewButton.setObjectName("addNewButton")
        self.sitesGridLayout.addWidget(self.addNewButton, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox1.setText("")
        self.checkBox1.setObjectName("checkBox1")
        self.sitesGridLayout.addWidget(self.checkBox1, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBox2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox2.setText("")
        self.checkBox2.setObjectName("checkBox2")
        self.sitesGridLayout.addWidget(self.checkBox2, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.site1 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.site1.setMaximumSize(QtCore.QSize(16777215, 31))
        self.site1.setObjectName("site1")
        self.sitesGridLayout.addWidget(self.site1, 2, 0, 1, 1)
        self.site2 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.site2.setMaximumSize(QtCore.QSize(16777215, 31))
        self.site2.setObjectName("site2")
        self.sitesGridLayout.addWidget(self.site2, 3, 0, 1, 1)
        self.setDurationLabel = QtWidgets.QLabel(self.centralwidget)
        self.setDurationLabel.setGeometry(QtCore.QRect(310, 279, 141, 31))
        self.setDurationLabel.setObjectName("setDurationLabel")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 309, 266, 63))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.durationGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.durationGridLayout.setContentsMargins(0, 0, 0, 0)
        self.durationGridLayout.setObjectName("durationGridLayout")
        self.minutesLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.minutesLabel.setObjectName("minutesLabel")
        self.durationGridLayout.addWidget(self.minutesLabel, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.hoursLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.hoursLabel.setObjectName("hoursLabel")
        self.durationGridLayout.addWidget(self.hoursLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.hoursField = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.hoursField.setMaximumSize(QtCore.QSize(16777215, 31))
        self.hoursField.setObjectName("hoursField")
        self.durationGridLayout.addWidget(self.hoursField, 1, 0, 1, 1)
        self.minutesField = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.minutesField.setMaximumSize(QtCore.QSize(16777215, 31))
        self.minutesField.setObjectName("minutesField")
        self.durationGridLayout.addWidget(self.minutesField, 1, 1, 1, 1)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(270, 40, 231, 51))
        self.titleLabel.setObjectName("titleLabel")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(320, 410, 111, 31))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blockedSitesLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Blocked Sites</span></p></body></html>"))
        self.blockedLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Blocked</span></p></body></html>"))
        self.deleteButton2.setText(_translate("MainWindow", "Delete"))
        self.deleteButton1.setText(_translate("MainWindow", "Delete"))
        self.addNewButton.setText(_translate("MainWindow", "Add New"))
        self.setDurationLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">Set Duration</span></p></body></html>"))
        self.minutesLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Minutes</span></p></body></html>"))
        self.hoursLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Hours</span></p></body></html>"))
        self.hoursField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.minutesField.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Web Blocker</span></p></body></html>"))
        self.saveButton.setText(_translate("MainWindow", "Save"))

    def connectActions(self, MainWindow):
        self.saveButton.clicked.connect(self.clicked)
        #self.addNewButton.clicked.connect(self.clicked)
        self.addNewButton.clicked.connect(self.newRow)


    def clicked(self):
        print("button was clicked")

    def newRow(self):
        print("adding new row...")
        # Add functionality for adding a new row here!
        #
        #



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.connectActions(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
